language: node_js

node_js:
  - "7.10.1"
  - "8.9"

sudo: false
cache:
  directories:
    - node_modules

script:
  - "npm test"

after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"